# Generated by Django 5.2.17 on 2026-09-29 17:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=280)),
                ('property_type', models.CharField(choices=[('agricultural_land', 'Agricultural Land / Farmland'), ('residential_land', 'Residential Plot / Land'), ('commercial_land', 'Commercial Land'), ('industrial_land', 'Industrial Land'), ('house', 'House / Single Family Home'), ('apartment', 'Apartment / Condominium'), ('commercial_building', 'Commercial Building / Office'), ('ranch', 'Ranch / Acreage')], max_length=40)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('pending', 'Pending / Under Review'), ('sold', 'Sold'), ('unpublished', 'Unpublished'), ('rejected', 'Rejected')], default='published', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('area_sqft', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('area_acres', models.FloatField(blank=True, null=True)),
                ('description', models.TextField()),
                ('short_description', models.CharField(blank=True, max_length=300)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(default='United States', max_length=100)),
                ('zip_code', models.CharField(blank=True, max_length=20)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('bedrooms', models.IntegerField(blank=True, null=True)),
                ('bathrooms', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('zoning_classification', models.CharField(blank=True, default='', max_length=100)),
                ('road_access', models.BooleanField(default=True)),
                ('water_rights', models.BooleanField(default=False)),
                ('electricity', models.BooleanField(default=True)),
                ('soil_type', models.CharField(blank=True, default='', max_length=100)),
                ('topography', models.CharField(blank=True, default='', max_length=100)),
                ('property_tax_annual', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Properties',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.CharField(blank=True, default='', max_length=500)),
                ('image_file', models.ImageField(blank=True, null=True, upload_to='properties/')),
                ('is_cover', models.BooleanField(default=False)),
                ('caption', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.property')),
            ],
            options={
                'ordering': ['-is_cover', 'id'],
            },
        ),
    ]
